services:
  store-app:
    build:
      context: ./store-app
      dockerfile: Dockerfile
    container_name: store-app
    ports:
      - "3000:3000"
    restart: unless-stopped

  cart-app:
    build:
      context: ./cart-app
      dockerfile: Dockerfile
    container_name: cart-app
    ports:
      - "3001:3000"
    restart: unless-stopped
