services:
  store-app:
    build:
      context: . # Build from the root of the project
      dockerfile: Dockerfile
      args:
        APP_NAME: store-app # Tell Docker which app to build
    container_name: store-app
    ports:
      - "3000:3000"
    restart: unless-stopped

  cart-app:
    build:
      context: . # Build from the root of the project
      dockerfile: Dockerfile
      args:
        APP_NAME: cart-app # Tell Docker which app to build
    container_name: cart-app
    ports:
      - "3001:3000"
    restart: unless-stopped
